Initiate travis fix errors (#2)
* Fix travis error unused parameter 

unused parameter 'BattlemasterGuid'

* Fix travis error unused parameter 

/home/travis/build/milestorme/azerothcore-wotlk/modules/mod-cfbg/src/CFBG_SC.cpp:146:102: fatal error: unused parameter 'BGTypeID' [-Wunused-parameter]

* Fix travis unused parameter 

/home/travis/build/milestorme/azerothcore-wotlk/modules/mod-cfbg/src/CFBG_SC.cpp:177:91: fatal error: unused parameter 'msg' [-Wunused-parameter]
903    void OnBeforeSendChatMessage(Player* player, uint32& type, uint32& lang, std::string& msg) override